import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 * 1.The program should display a menu as follows:
 * MENU
 * [1] Prime or Composite
 * [2] All Prime Numbers
 * [3] Exit
 * Choose an option
 * 2. Option 1 should ask for an integer from the user and displays a corresponding comment as “Prime Number”, “Composite Number”, or “Neither Prime nor Composite”.
 * 3. Zero and 1 are neither prime nor composite, -1 is prime, while all other negative numbers are composite.
 * 4. Option 2 should ask for an entry of two integers.  It should determine and display all prime numbers between the two integers (including the two integers, if they are prime). For example, if 3 and 11 are entered, the display should be: 3, 5, 7, 11
 * 5. The program returns to the main menu after each display from the option and when an invalid input of the option is encountered.
 * 6. Validate the option input.  Only 1, 2 and 3 are acceptable, otherwise, display a message error and return to the main menu.
 * 7. Exit option terminates the program.
 */

public class MP1_Alaraj_Abdulsalam {
    public static void main(String[] args) {
        boolean loop;
        do {
            loop = false;
            System.out.println("\n\t MENU");
            System.out.println("[1] Prime or Composite");
            System.out.println("[2] All Prime Numbers");
            System.out.println("[3] Exit");

            Scanner scan = new Scanner(System.in);
            int choice = scan.nextInt();

            switch (choice) {
                case 1:
                    int userInput;
                    // Accepting user input
                    System.out.print("Enter a number: ");
                    userInput = scan.nextInt();

                    // Evaluating the user input using the generateIsPrimeMessage function
                    String msg = generateIsPrimeMessage(userInput);

                    // Display the message generated by the generateIsPrimeMessage function
                    System.out.println(msg);
                    loop = true;
                    break;
                case 2:
                    System.out.print("Enter first number: ");
                    int low = scan.nextInt();
                    System.out.print("Enter another number: ");
                    int high = scan.nextInt();

                    if (low > high) {
                        System.out.println("Error: the first number should be lower than the second number");
                        loop = true;
                        break;
                    }

                    StringBuilder result = new StringBuilder();

                    while (low <= high) {
                        boolean flag = false;

                        for (int i = 2; i <= low / 2; i++) {
                            if (low % i == 0) {
                                flag = true;
                                break;
                            }
                        }

                        if (!flag && low != 0 && low != 1) {
                            result.append(low).append(", ");
                        }

                        low++;
                    }

                    System.out.println(result);
                    loop = true;
                    break;
                case 3:
                    break;
                default:
                    loop = true;
                    System.out.println("Invalid input");
            }
        } while (loop);
    }

    /**
     * A function to check if the passed number is prime or composite
     * and returns a message string
     */
    private static String generateIsPrimeMessage(int n) {
        String msg = "Invalid input";

        for (int i = 2; i <= n / 2; i++) {
            msg = "Prime Number";

            if (n % i == 0) {
                msg = "Composite Number";
            }
        }

        if (n < -1) {
            msg = "Composite Number";
        }

        if (n == -1) {
            msg = "Prime Number";
        }

        if (n == 1 || n == 0) {
            msg = "Neither Prime nor Composite";
        }

        return msg;
    }
}
